### ISSUE TITLE
Add Lando services for install and htaccess

### ISSUE THREAD

**Issue by UTCGilligan** [UTCWeb/utctiny#14]
As in [UTCBlogsMultisite](https://github.com/UTCWeb/utcblogsmultisite/blob/develop/.lando.yml):
```
services:
  appserver:
    run:
      - cd $LANDO_MOUNT && composer install
      - cd $LANDO_MOUNT && cp htaccess.example /.htaccess
```
